### ISSUE TITLE
Binary descriptor

### ISSUE THREAD

**Issue by ceccocats** [MagicLeapResearch/SuperPointPretrainedNetwork#23]
Is it somehow possible to convert/train the float descriptor to binary?
My pipeline is fully optimized for HAMMING distance matching so it would be nice to have the binary descriptor out of superpoint.

thanks,
Francesco

**Comment by guker** [comment]
Do you have succeeded to convert float descriptor to binary？

**Comment by Alex-Beh** [comment]
Hi, any conclusion on this topic? I am facing the similar issue and curious about whether I can use euclidean distance to compare two Superpoint descriptors.
