### ISSUE TITLE
How to get feature descriptor for a patch?

### ISSUE THREAD

**Issue by abhinavtripathi95** [MagicLeapResearch/SuperPointPretrainedNetwork#5]
Hi,
I wanted to get the HPatches [benchmark](https://github.com/hpatches/hpatches-benchmark) score for SuperPoint. But to eliminate detector related factors, I want to have a feature vector describing 65x65 patches from the dataset.

How can I use the provided pre-trained model to get the descriptor on a 65x65 image patch?

**Comment by quantombone** [comment]
SuperPoint works on the entire input image (generally something like 240x320, and no bigger than 480x640) and does not give a descriptor for an input patch like many other systems. 

SuperPoint is a fully convolutional network so you can also use the descriptor field produced by the network for mostly arbitrary image sizes (multiple of 8 pixels). If you give it a 32x32 input, you can get a 4x4 descriptor field of 256-D descriptors.
