### ISSUE TITLE
MagicPoint

### ISSUE THREAD

**Issue by thomasstats** [MagicLeapResearch/SuperPointPretrainedNetwork#6]
Although the readme states that the synthetic shapes dataset or the training dataset, is there any plan to release the initial detector of MagicPoint?

Forgive me if this has been released already, or there's mention of it not being released elsewhere.

**Comment by ddetone** [comment]
Unfortunately we don't plan to release the initial MagicPoint detector. You might want to check out this repo: https://github.com/rpautrat/SuperPoint as a starting point for creating your own synthetic shapes dataset.
