### ISSUE TITLE
time cost of superpoint feature extraction

### ISSUE THREAD

**Issue by Jemmagu** [MagicLeapResearch/SuperPointPretrainedNetwork#9]
Hi @ddetone , I'm curious about the time cost of superpoint feature extraction.

You mentioned in your paper that you estimate the total runtime of the system on a GPU
to be about 13ms. But when I extracted superpoint features, (640*480, with RGB 3 channel ), using single GPU (Tesla P100 PCIe 16GB), the time cost is about 60ms. Is that normal? Or have you calculated the time cost yourself and you may guess what's wrong with my 60ms.

Thanks in advance! Really hope to get your reply!

**Comment by ddetone** [comment]
When I initially benchmarked it, I was only counting the time it spent to extract the coarse detector and descriptor outputs (no post processing like NMS, descriptor sampling, etc) which in this repo is done on the CPU.

You might also want to check out a newer implementation of SuperPoint here (https://github.com/magicleap/SuperGluePretrainedNetwork)  that does the post-processing on the GPU. I think you'll find you can get something very close to 13ms for the entire pipeline (images -> points).

**Comment by ynma-hanvo** [comment]
on my gt1660ti gpu,  takes about 40ms.  hope it can be faster

**Comment by guker** [comment]
on snapdragon dsp v69， superpoint take about 1.5ms on 240x320 size

**Comment by cavalleria** [comment]
@guker Great, I have a few questions. Does the 1.5ms include post-processing (such as nms_fast)? Is it an int8 model? How is the accuracy?"
